version: "2"

linters:
  default: none
  enable:
    - loglinter

  settings:
    custom:
      loglinter:
        type: module
        description: "Log message rules"
        settings:
          requireLowercaseStart: true
          englishMode: "ascii"
          forbidSpecialChars: true
          allowedCharsRegex: "^[a-zA-Z0-9 ,.:?'_-]+$"
          forbidSensitive: true
          sensitiveKeywords:
            - password
            - passwd
            - secret
            - apikey
            - token
            - api_key
            - credential
            - key